### ISSUE TITLE
sdl-hellow-world crashes in Ryujinx but spacenx is fine

### ISSUE THREAD

**Issue by minkcv** [vgmoose/sdl-hello-world#1]
I was able to run your spacenx game in Ryujinx but not this hello world example. I'm having the same issue in Ryujinx with my game and was wondering if you could take a look.

**Comment by vgmoose** [comment]
Is this with the release nro or self-compiled?

The release nro is compiled with libtransistor, but the repo (and spacenx’s release is) can be compiled with libnx too.

Either way, it’s probably best to ask for help on the Ryujinx discord, they are pretty good about fixing emulation issues that work on hardware.

**Comment by minkcv** [comment]
Ah. Neither game works when compiled with libnx. I'm having issues getting libtransistor to work. Specifically, the sdl-libtransistor 

    make -f switch.mk 

Results in the following on Ubuntu and msys2 in windows

    checking whether the C compiler works... no

I do have llvm and clang installed. 
The Ryujinx people are great. I've had them fix issues before.

**Comment by vgmoose** [comment]
I meant good* not oof 😄  They're very responsive and quick to fix issues!

Regarding libtransistor, I found this guide to be pretty thorough: https://reswitchedweekly.github.io/Development-Setup/

There's also this package on AUR for arch linux:
https://aur.archlinux.org/packages/libtransistor-bin/

Personally, I haven't tried anything libtransistor on windows, and I think libnx may have better support for building on windows based on seeing what other people are making.

**Comment by minkcv** [comment]
I've got libtransistor working, it's the sdl-libtransistor that is the issue. There is only one commit on the switch.mk so maybe it's just not working. 

Have you tried your libnx built nro on a real switch? I'm afraid to try it if it's not working in Ryujinx.

**Comment by minkcv** [comment]
I tried my game on the switch and it works GREAT with libnx and switch-sdl2.

**Comment by vgmoose** [comment]
yeah both nro's have worked on a real switch, at last check (the one for download is a libtransistor one too)

Glad to hear you got it working!
